### ISSUE TITLE
sbin install location

### ISSUE THREAD

**Issue by nathanhaigh** [markfasheh/ocfs2-tools#1]
I'm playing around with building on Ubuntu 14.04 and tried:

```bash
./configure --prefix=/tmp/ocfs2-tools
make
make install
```

However, the install is attempting to copy the following files directly under `/sbin/`:

```
o2image
mount.ocfs2
ocfs2_hb_ctl
o2cb
o2cb_ctl
debugfs.ocfs2
o2cluster
tunefs.ocfs2
mounted.ocfs2
mkfs.ocfs2
fsck.ocfs2
```

Is this expected behaviour!?

**Comment by josephhz** [comment]
Hi,
currently ocfs2 tools can only be installed into /sbin.
In kernel module, tools path is hard coding, such as:
static char ocfs2_hb_ctl_path[OCFS2_MAX_HB_CTL_PATH] = "/sbin/ocfs2_hb_ctl";
