### ISSUE TITLE
incorrect FSF address in several source files

### ISSUE THREAD

**Issue by cheese** [markfasheh/ocfs2-tools#11]
I build rpms of ocfs2-tools on Fedora, and run rpmlint over them. rpmlint reports several files use incorrect FSF address.

ocfs2console.x86_64: E: incorrect-fsf-address /usr/lib64/python2.7/site-packages/ocfs2interface/__init__.py
ocfs2console.x86_64: E: incorrect-fsf-address /usr/lib64/python2.7/site-packages/ocfs2interface/console.py
ocfs2console.x86_64: E: incorrect-fsf-address /usr/lib64/python2.7/site-packages/ocfs2interface/about.py
ocfs2console.x86_64: E: incorrect-fsf-address /usr/lib64/python2.7/site-packages/ocfs2interface/format.py
ocfs2console.x86_64: E: incorrect-fsf-address /usr/lib64/python2.7/site-packages/ocfs2interface/bosa.py
ocfs2console.x86_64: E: incorrect-fsf-address /usr/lib64/python2.7/site-packages/ocfs2interface/partitionview.py
ocfs2console.x86_64: E: incorrect-fsf-address /usr/lib64/python2.7/site-packages/ocfs2interface/classlabel.py
ocfs2console.x86_64: E: incorrect-fsf-address /usr/lib64/python2.7/site-packages/ocfs2interface/process.py
ocfs2console.x86_64: E: incorrect-fsf-address /usr/lib64/python2.7/site-packages/ocfs2interface/pushconfig.py
ocfs2console.x86_64: E: incorrect-fsf-address /usr/lib64/python2.7/site-packages/ocfs2interface/terminal.py
ocfs2console.x86_64: E: incorrect-fsf-address /usr/lib64/python2.7/site-packages/ocfs2interface/confdefs.py
ocfs2console.x86_64: E: incorrect-fsf-address /usr/lib64/python2.7/site-packages/ocfs2interface/fstab.py
ocfs2console.x86_64: E: incorrect-fsf-address /usr/lib64/python2.7/site-packages/ocfs2interface/toolbar.py
ocfs2console.x86_64: E: incorrect-fsf-address /usr/lib64/python2.7/site-packages/ocfs2interface/ipwidget.py
ocfs2console.x86_64: E: incorrect-fsf-address /usr/lib64/python2.7/site-packages/ocfs2interface/menu.py
ocfs2console.x86_64: E: incorrect-fsf-address /usr/lib64/python2.7/site-packages/ocfs2interface/nodeconfig.py
ocfs2console.x86_64: E: incorrect-fsf-address /usr/lib64/python2.7/site-packages/ocfs2interface/guiutil.py
ocfs2console.x86_64: E: incorrect-fsf-address /usr/lib64/python2.7/site-packages/ocfs2interface/mount.py
ocfs2console.x86_64: E: incorrect-fsf-address /usr/lib64/python2.7/site-packages/ocfs2interface/fswidgets.py
ocfs2console.x86_64: E: incorrect-fsf-address /usr/lib64/python2.7/site-packages/ocfs2interface/general.py
ocfs2console.x86_64: E: incorrect-fsf-address /usr/lib64/python2.7/site-packages/ocfs2interface/ls.py
ocfs2console.x86_64: E: incorrect-fsf-address /usr/lib64/python2.7/site-packages/ocfs2interface/tune.py
ocfs2console.x86_64: E: incorrect-fsf-address /usr/lib64/python2.7/site-packages/ocfs2interface/fsck.py
ocfs2console.x86_64: E: incorrect-fsf-address /usr/lib64/python2.7/site-packages/ocfs2interface/o2cb_ctl.py
ocfs2-tools.x86_64: E: incorrect-fsf-address /usr/share/doc/ocfs2-tools/COPYING
ocfs2-tools-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/ocfs2-tools-ocfs2-tools-1.8.5/include/ocfs2/kernel-rbtree.h
ocfs2-tools-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/ocfs2-tools-ocfs2-tools-1.8.5/libocfs2/kernel-rbtree.c
ocfs2-tools-devel.x86_64: E: incorrect-fsf-address /usr/include/ocfs2/kernel-rbtree.h

**Comment by josephhz** [comment]
Fixed by commit 70aec706fa87 ("Update FSF address in GPL2 license").
