### ISSUE TITLE
How to build ocfs2-tools on Ubuntu?

### ISSUE THREAD

**Issue by kaleo211** [markfasheh/ocfs2-tools#2]

**Comment by markfasheh** [comment]
Can you be more precise with your question - did you try building, and what problems did you run into doing so?

**Comment by kaleo211** [comment]
@markfasheh Hi, we are building this repo by `./autogen.sh && make`.
But when we run `o2cb_ctl`, it shows error `modprobe: FATAL: Module ocfs2_stack_o2cb not found.
modprobe: FATAL: Module ocfs2 not found.` 
It seems like it doesn't install ocfs2 service automatically, correct?

**Comment by goldwynr** [comment]
On 06/27/2016 07:48 AM, Xuebin He wrote:
> @markfasheh <https://github.com/markfasheh> Hi, we are building this
> repo by |./autogen.sh && make|.
> But when we run |o2cb_ctl|, it shows error |modprobe: FATAL: Module
> ocfs2_stack_o2cb not found.
> modprobe: FATAL: Module ocfs2 not found.|
> It seems like it doesn't install ocfs2 service automatically, correct?
> 

This means you don't have ocfs2_stack_o2cb and other ocfs2 modules in
your kernel. Please enable the module and recompile the kernel.


-- 
Goldwyn
