### ISSUE TITLE
configure does not find ncurses libs

### ISSUE THREAD

**Issue by Thermi** [markfasheh/ocfs2-tools#21]
Hi,

I got ncurses installed, but configure doesn't find it.

```
pkg-config --libs ncurses
-lncursesw -ltinfo
```
```
checking for libaio.h... yes
checking for tgetstr in -lncurses... no
configure: error: Unable to find ncurses library
```

Please advise.

**Comment by josephhz** [comment]
Install ncurses-devel and try again.

**Comment by jsteel44** [comment]
I have this problem too, on Arch Linux and there is no ncurses-devel package but there's ncurses-full in the AUR and that gets me past this error.

**Comment by Thermi** [comment]
My point is that ncursesw is the ncurses library that supplies the same functionality as nrcurses, but has multi byte character support, which is better than just single byte character support. The two libs are source compatible, so if you check for and use ncursesw instead of ncurses, if it does not exist, it works OOTB just fine.
