### ISSUE TITLE
build failed with glibc 2.28

### ISSUE THREAD

**Issue by cheese** [markfasheh/ocfs2-tools#31]
Since glibc git 663e7d78 (to be 2.28), type loff_t will be only defined
when _DEFAULT_SOURCE defined. And with _XOPEN_SOURCE defined, _DEFAULT_SOURCE
will not be defined by default.

Build failed with

```
make[1]: Entering directory '/builddir/build/BUILD/ocfs2-tools-ocfs2-tools-1.8.5/libo2cb'
gcc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -mcet -fcf-protection -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -pipe -fPIC -I../include -I. -DHAVE_CMAP -DHAVE_FSDLM -MD -MP -MF ./.o2cb_abi.d -o o2cb_abi.o -c o2cb_abi.c
In file included from o2cb_abi.c:52:
../include/ocfs2/ocfs2.h:222:2: error: unknown type name 'loff_t'
loff_t d_off; /* Offset of structure in the file */
^~~~~~
```

There are ways to fix this issue:
1. Explicitly define _DEFAULT_SOURCE in all source that define _XOPEN_SOURCE
2. Replace loff_t with off64_t, but this change some sources to include ocfs2.h first.
3. Replace loff_t with int64_t, but this breaks type semantics.

**Comment by ganghe** [comment]
The fix patch is here, 
https://github.com/markfasheh/ocfs2-tools/commit/e6e049ca6a371528ebf39b106209c2df586500bc

close this issue.
