### ISSUE TITLE
Github Releases

### ISSUE THREAD

**Issue by Thermi** [markfasheh/ocfs2-tools#36]
Hello,

There haven't been any releases since 2017 but there are lots of changes piled up that are needed. Could you please tag and public a stable release (and preferably in the regularly in the future as well), so we maintainers (I'm maintaining it on the AUR) can follow along without having to pick out single patches?

Kind regards

Thermi

**Comment by josephhz** [comment]
@ganghe Could you please do a favor for us? Thanks.

**Comment by josephhz** [comment]
I've just pushed a new tag ocfs2-tools-1.8.6. Please check.
