### ISSUE TITLE
Kernel errors during mount

### ISSUE THREAD

**Issue by vvidic** [markfasheh/ocfs2-tools#46]
During mount of ocfs2, a strange error is printed by the kernel mentioning floppy device.
The mount itself is successful but not sure why the message appears?

```
[  124.975017] ocfs2: Mounting device (7,0) on (node 1, slot 0) with ordered data mode.
[  125.027710] blk_update_request: I/O error, dev fd0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[  125.029687] floppy: error 10 while reading block 0
[  125.027710] blk_update_request: I/O error, dev fd0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[  125.029687] floppy: error 10 while reading block 0
[  125.127751] blk_update_request: I/O error, dev fd0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[  125.132061] floppy: error 10 while reading block 0
[  125.127751] blk_update_request: I/O error, dev fd0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[  125.132061] floppy: error 10 while reading block 0
```

**Comment by josephhz** [comment]
Which kernel do you use? And do you mount ocfs2 upon floppy disk?

**Comment by vvidic** [comment]
On Sun, Jan 12, 2020 at 05:22:07PM -0800, Joseph Qi wrote:
> Which kernel do you use? And do you mount ocfs2 upon floppy disk?

Here is some more info:

Linux debian 5.4.0-2-amd64 #1 SMP Debian 5.4.8-1 (2020-01-05) x86_64

brw-rw---- 1 root disk 7, 0 Jan 13 19:02 /dev/loop0

[  101.484649] ocfs2: Mounting device (7,0) on (node 0, slot 0) with ordered data mode.
[  101.616940] blk_update_request: I/O error, dev fd0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[  101.621802] floppy: error 10 while reading block 0
[  101.616940] blk_update_request: I/O error, dev fd0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[  101.621802] floppy: error 10 while reading block 0
[  101.720939] blk_update_request: I/O error, dev fd0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[  101.726010] floppy: error 10 while reading block 0
[  101.720939] blk_update_request: I/O error, dev fd0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[  101.726010] floppy: error 10 while reading block 0

-- 
Valentin

**Comment by vvidic** [comment]
This seems to be something related to floopy module loaded in KVM, so closing.
