### ISSUE TITLE
No reflink utility

### ISSUE THREAD

**Issue by nikaro** [markfasheh/ocfs2-tools#47]
Hello,

There is a reflink functionnality mentionned in the manpage, but how to use it is not documented.

Oracle documentation and [blog](https://blogs.oracle.com/wim/ocfs2-reflink) mention a `reflink` command line utility that cannot be found in this package.

Am i missing something ?

Regards.

**Comment by josephhz** [comment]
Seems the reflink tool is not merged into ocfs2-tools master. The original patches can be found here:
https://oss.oracle.com/git/gitweb.cgi?p=jlbec/reflink.git;a=summary

**Comment by nikaro** [comment]
Ah... my bad. Thank you.
