### ISSUE TITLE
o2cb service doesn't have online/offline/configure commands on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by DoobleD** [markfasheh/ocfs2-tools#50]
On Ubuntu 20.04 the service `o2cb` have some important commands missing, such as `online`, `offline`, and `configure`. The issue doesn't happen on Ubuntu 18.04 and below.

Ubuntu 18.04:
```
$ o2cb --version
o2cb 1.8.5
$ sudo service o2cb something
Usage: /etc/init.d/o2cb {start|stop|restart|force-reload|enable|disable|configure|load|unload|online|offline|force-offline|status|online-status}
```

Ubuntu 20.04:
```
$ o2cb --version
o2cb 1.8.6
$ sudo service o2cb online
Usage: /etc/init.d/o2cb {start|stop|status|restart|try-restart|force-reload}
```

In both cases I installed `o2cb` via:
```
$ sudo apt-get update && sudo apt-get install ocfs2-tools -y
```

Is there something I am missing? The [manpage](http://manpages.ubuntu.com/manpages/focal/man7/o2cb.7.html) for Ubuntu 20.04 does mention the `online` command.

**Comment by josephhz** [comment]
Checked './vendor/common/o2cb.init.sh' and it looks good, and there is no difference bettwen 1.8.5 and 1.8.6.

From the output you list out:
Usage: /etc/init.d/o2cb {start|stop|status|restart|try-restart|force-reload}

It seems that it is 'ocfs2.init' but not 'o2cb.init'，so I think ubuntu 20.04 misuses the two.

**Comment by DoobleD** [comment]
Thank you for the prompt answer @josephhz! The `ocfs2` service does show the same output indeed.

I've reported a bug on the ubuntu package [here](https://bugs.launchpad.net/ubuntu/+source/ocfs2-tools/+bug/1939406). In the meantime I'm trying alternative solutions. I've installed the package from ubuntu 18.04 on 20.4 but I'm getting some `Module ocfs2_dlmfs not found` errors when starting `o2cb`. I then tried installing from source but the [documentation](https://github.com/markfasheh/ocfs2-tools/blob/master/documentation/users_guide.txt) seems outdated and I couldn't find up to date directions.

Do you have any other idea or suggestion?

**Comment by josephhz** [comment]
If o2cb init script is the only issue you've encountered, I think you can take the following workaround before ubuntu gets it final fixed.
1. check out tag 'ocfs2-tools-1.8.6' from source tree, and build.
2. replace /etc/init.d/o2cb with the newly built one.
# cp /etc/init.d/o2cb /etc/init.d/o2cb.bak
# cp ocfs2-tools/vendor/common/o2cb.init /etc/init.d/o2cb

**Comment by DoobleD** [comment]
Worked like a charm, thanks @josephhz!
