### ISSUE TITLE
configure: error: Unable to find com_err library

### ISSUE THREAD

**Issue by yongshengma** [markfasheh/ocfs2-tools#56]
Hello,

I ran `./autogen.sh` in CentOS 8.1 but I got error as

```
checking for com_err... checking for com_err in -lcom_err... no
configure: error: Unable to find com_err library
```

Libcom_err-1.44 was installed. 

Any idea about it?

Sincerely,
Yongsheng

**Comment by josephhz** [comment]
You need install libcom_err-devel.

**Comment by yongshengma** [comment]
> You need install libcom_err-devel.

Yes. thanks. All the additional devel pkgs are also needed:

`
e2fsprogs-devel-1.45.6-2.el8.x86_64
libcom_err-devel-1.45.6-2.el8.x86_64

libuuid-devel-2.32.1-28.el8.x86_64
libaio-devel-0.3.112-1.el8.x86_64

ncurses-devel-6.1-9.20180224.el8.x86_64
ncurses-c++-libs-6.1-9.20180224.el8.x86_64

readline-devel-7.0-10.el8.x86_64

glib2-devel-2.56.4-156.el8.x86_64
pcre-8.42-6.el8.x86_64
pcre-cpp-8.42-6.el8.x86_64
pcre-devel-8.42-6.el8.x86_64
pcre-utf32-8.42-6.el8.x86_64
pcre-utf16-8.42-6.el8.x86_64

`
