### ISSUE TITLE
About ocfs2-tools version planning？

### ISSUE THREAD

**Issue by Heng-Evans** [markfasheh/ocfs2-tools#59]
hi, @josephhz 
It has been more than two years since the last version, what is the version plan?
Is it possible to release a new version with some bug fixes or new features?

**Comment by josephhz** [comment]
Hi, actually ocfs2 doesn't have any new feature development plan, just few bugfixes. So does ocfs2 tools.
Anyway, I can tag the HEAD as a new micro version if you requires.

**Comment by Heng-Evans** [comment]
That would be great if you can tag the HEAD, thanks for replying.

**Comment by josephhz** [comment]
Done now.
