### ISSUE TITLE
Under specific conditions, the mkfs result appears incorrect

### ISSUE THREAD

**Issue by Byte-Jerry** [markfasheh/ocfs2-tools#60]
After Executing the command "mkfs.ocfs2 -C 32k -J block64 [dev] -x" to mkfs a device with a size of about 129T, but the corresponding ocfs2 volume size is only about 1T. The "mkfs" command produces the following output:
`Volume size: 1099509530624 (33554368 clusters) (268434944 blocks)`
I checked the global_bitmap and its total bit is only 33554368,  consistent with the above result.

I checked the code of mkfs and found that the error occurred at the following code section of fill_defaults() function . In the first line of the following code section，'s->volume_size_in_bytes' is of type uint64_t , 's->volume_size_in_clusters' is of type uint32_t. When the device size exceeds 128T and the Cluster_size is specified as 32k, the calculation result on the right side will exceed the maximum value of uint32_t, resulting in the truncated result in 's->volume_size_in_clusters'.  Later, because the volume size needs to be cluster aligned, the wrong result is passed to 's->volume_size_in_bytes'，resulting in an incorrect mkfs result.
```
    <mkfs.ocfs2/mkfs.c>
    s->volume_size_in_clusters = s->volume_size_in_bytes >> s->cluster_size_bits;
    tmp = (uint64_t)s->volume_size_in_clusters;
    s->volume_size_in_bytes = tmp << s->cluster_size_bits;
    s->volume_size_in_blocks = s->volume_size_in_bytes >> s->blocksize_bits;
```

Will changing the member volume_size_in_clusters in struct _State to type uint64_t make the program more reliable?

**Comment by josephhz** [comment]
Umm... I think this is by design.
OCFS2 supports the maximum volume size of 4PB with block size 4k and cluster size 1M.
For your case, block size 4k and cluster size is 32k, so the maximum volume size is 128T.

**Comment by josephhz** [comment]
Umm... I think this is by design.
OCFS2 supports the maximum volume size of 4PB with block size 4k and cluster size 1M.
For your case, block size 4k and cluster size is 32k, so the maximum volume size is 128T.

**Comment by aLearnerofpy** [comment]
> Umm... I think this is by design. OCFS2 supports the maximum volume size of 4PB with block size 4k and cluster size 1M. For your case, block size 4k and cluster size is 32k, so the maximum volume size is 128T.

Thank you for your answer.
It is possible by design to limit the supported volume size, but the mkfs.ocfs2 error results and  the message that the execution was successful confuse me.

**Comment by josephhz** [comment]
Yes, it seems that we add a check and fail in this case may be more proper.
